name: Docker Image CI for GHCR
on: 
  push
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
           - ​name​: ​Login to GHCR 
​             ​uses​: ​docker/login-action@v1  
​             ​with​: 
​                 ​registry​: ​ghcr.io 
​        ​         username​: ​${{ secrets.GHCR_USERNAME }} 
​        ​         password​: ​${{ secrets.GHCR_TOKEN }}
          docker build . --tag ghcr.io/dogclassifier/actions-runner-controller:latest
          docker push ghcr.io/dogclassifier/actions-runner-controller:latest
